<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <PropertyGroup>
        <AssemblyVersion>$(UltralightVersion)</AssemblyVersion>
        <FileVersion>$(UltralightVersion)</FileVersion>
        <ProductVersion>$(UltralightVersion)</ProductVersion>
        <ApplicationVersion>$(UltralightVersion)</ApplicationVersion>
        <InformationalVersion>$(UltralightVersion)</InformationalVersion>
        <Version>$(UltralightVersion)</Version>
    </PropertyGroup>
    
    <PropertyGroup>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>

        <PackageLicenseExpression></PackageLicenseExpression>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="LICENSE.txt" Pack="true" PackagePath="LICENSE.txt"/>
        <None Include="EULA.txt" Pack="true" PackagePath="EULA.txt"/>
        <None Include="NOTICES.md" Pack="true" PackagePath="NOTICES.md"/>
    </ItemGroup>

    <ItemGroup>
        <_NativeAssetName Include="runtimes/win-x64/native/Ultralight.dll" PackagePath="runtimes/win-x64/native"/>
        <_NativeAssetName Include="runtimes/win-x64/native/UltralightCore.dll" PackagePath="runtimes/win-x64/native"/>
        <_NativeAssetName Include="runtimes/win-x64/native/WebCore.dll" PackagePath="runtimes/win-x64/native"/>

        <_NativeAssetName Include="runtimes/osx-x64/native/libUltralight.dylib" PackagePath="runtimes/osx-x64/native"/>
        <_NativeAssetName Include="runtimes/osx-x64/native/libUltralightCore.dylib" PackagePath="runtimes/osx-x64/native"/>
        <_NativeAssetName Include="runtimes/osx-x64/native/libWebCore.dylib" PackagePath="runtimes/osx-x64/native"/>

        <_NativeAssetName Include="runtimes/linux-x64/native/libUltralight.so" PackagePath="runtimes/linux-x64/native"/>
        <_NativeAssetName Include="runtimes/linux-x64/native/libUltralightCore.so" PackagePath="runtimes/linux-x64/native"/>
        <_NativeAssetName Include="runtimes/linux-x64/native/libWebCore.so" PackagePath="runtimes/linux-x64/native"/>

        <_ExistingAssets Include="@(_NativeAssetName)"/>
        <Content Include="@(_ExistingAssets->'%(Identity)')" CopyToOutputDirectory="PreserveNewest" PackagePath="%(PackagePath)" Pack="true"/>
    </ItemGroup>

</Project>
